server:
  port: 8081

auth:
  token:
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
    expirationInMils: 86400000

cookie:
  client:
    path: "http://localhost:5173"

spring:
  mail:
    host: ssl0.ovh.net
    port: 587
    username: projet-portail-enseignant@eilco-ulco.fr
    password: 0Eilco672
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000
          ssl:
            trust: "*"
        transport:
          protocol: smtp
        debug: true
        from: projet-portail-enseignant@eilco-ulco.fr

  
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/portail_eilco_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
