server:
  port: 8081

auth:
  token:
    expirationInMils: 3600000
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D

cookie:
  client:
    path: "http://localhost:5173"
spring:
  mvc:
    static-path-pattern: ./backend/uploads/**
  web:
    resources:
      static-locations: file:./backend/uploads/uploads/
  application:
    name: backend


  datasource:
    url: jdbc:mysql://localhost:3306/portail_eilco_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

    #show-sql: true

    hibernate:
      ddl-auto: update

